# -*- coding: utf-8 -*-
"""Customer_Personality_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6cYzuxss51mlMo9Lk2vAn2YOa3YiF9n
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split, GridSearchCV

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")

print("Path to dataset files:", path)

df = pd.read_csv(r"/kaggle/input/customer-personality-analysis/marketing_campaign.csv", sep="\t")

df.head(5)

df.info()

df.describe()

df.isnull().sum()

df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], dayfirst=True)

df["Customer_Year"] = df["Dt_Customer"].dt.year
df["Customer_Month"] = df["Dt_Customer"].dt.month
df["Customer_Day"] = df["Dt_Customer"].dt.day
df["Customer_Since_Days"] = (df["Dt_Customer"].max() - df["Dt_Customer"]).dt.days

sns.countplot(x="Response", data=df)
plt.title("Distribution of Target (Response)")
plt.show()

df = df.drop(columns=["ID", "Z_CostContact", "Z_Revenue"])

num_cols = df.select_dtypes(include=['int64','float64']).columns
df_num = df[num_cols]

plt.figure(figsize=(15,10))
df_num.hist(bins=20, layout=(5,5), color="skyblue", edgecolor="black")
plt.suptitle("Distribution of Numerical Features", fontsize=16)
plt.tight_layout()
plt.show()

cat_cols = df.select_dtypes(include=['object']).columns

plt.figure(figsize=(15,5))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(1, len(cat_cols), i)
    sns.countplot(x=col, data=df, order=df[col].value_counts().index, palette="Set2")
    plt.title(col)
    plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15,10))
for i, col in enumerate(num_cols, 1):
    plt.subplot(5, 5, i)
    sns.boxplot(x="Response", y=col, data=df)
    plt.title(col)
plt.tight_layout()
plt.show()


plt.figure(figsize=(15,5))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(1, len(cat_cols), i)
    sns.countplot(x=col, hue="Response", data=df, palette="Set2")
    plt.title(col)
    plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df

df.dtypes

df["Income"] = df["Income"].fillna(df["Income"].median())

df

df_clean = df.copy()
num_cols = df_clean.select_dtypes(include=[np.number]).columns

for col in num_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

"""### Refactoring Preprocessing with `ColumnTransformer` and `Pipeline`

To ensure consistency and reproducibility, we will create a unified preprocessing pipeline. This pipeline will handle:
1.  **Numerical Feature Scaling**: Apply `StandardScaler` to numerical columns.
2.  **Categorical Feature Encoding**: Apply `OneHotEncoder` to categorical columns.

This approach avoids inconsistencies in data scaling and feature engineering across different models, making the entire process more robust.
"""

# The 'Dt_Customer' column has been used to create new features, so it can now be dropped from the main DataFrame.
# Also, drop 'ID' (already done), 'Z_CostContact', and 'Z_Revenue' (already done) which were identified as irrelevant.
# Let's ensure these are dropped if they still exist after previous steps.

# Ensure 'Dt_Customer' is dropped as its information is already extracted into new columns
if 'Dt_Customer' in df.columns:
    df = df.drop(columns=['Dt_Customer'])

# Define features (X) and target (y)
X = df.drop('Response', axis=1)
y = df['Response']

# Identify numerical and categorical columns for the preprocessor
numerical_features = X.select_dtypes(include=np.number).columns.tolist()
categorical_features = X.select_dtypes(include='object').columns.tolist()

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # Handle any potential remaining NaNs
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create a full pipeline with preprocessing and a classifier (e.g., RandomForestClassifier)
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, class_weight='balanced')) # Added class_weight for imbalanced target
])

print("Preprocessing pipeline defined successfully.")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train the pipeline
model_pipeline.fit(X_train, y_train)

# Make predictions
y_pred_pipeline = model_pipeline.predict(X_test)

# Evaluate the model from the pipeline
print("\n--- Model Evaluation (RandomForestClassifier with Pipeline) ---")
print("Accuracy:", accuracy_score(y_test, y_pred_pipeline))
print("\nClassification Report:\n", classification_report(y_test, y_pred_pipeline))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_pipeline))

# Plot Confusion Matrix for the pipeline model
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, y_pred_pipeline), annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - RandomForest with Pipeline')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""This structured approach makes your code cleaner, easier to understand, and ensures that all preprocessing steps are applied consistently. This is a much better practice for projects you intend to showcase on GitHub and include in your CV!"""

df

df.dtypes

df.isna().sum()

def plot_feature_importance(model_pipeline, X_columns, title):
    # Get the fitted preprocessor from the pipeline
    preprocessor = model_pipeline.named_steps['preprocessor']

    # Get feature names after one-hot encoding
    ohe_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)

    # Combine numerical feature names and one-hot encoded categorical feature names
    # Ensure numerical_features are correctly ordered and matched
    processed_feature_names = numerical_features + list(ohe_feature_names)

    # Get the classifier from the pipeline
    classifier = model_pipeline.named_steps['classifier']

    # Check if the classifier has feature_importances_ attribute
    if hasattr(classifier, 'feature_importances_'):
        importances = classifier.feature_importances_

        # Create a pandas Series for easier sorting and plotting
        feature_importances = pd.Series(importances, index=processed_feature_names)

        # Sort features by importance
        feature_importances = feature_importances.sort_values(ascending=False)

        plt.figure(figsize=(12, 7))
        sns.barplot(x=feature_importances.values, y=feature_importances.index)
        plt.title(title)
        plt.xlabel("Feature Importance")
        plt.ylabel("Feature")
        plt.tight_layout()
        plt.show()
    else:
        print(f"Classifier {type(classifier).__name__} does not have feature_importances_ attribute.")

# Plot feature importance for the RandomForestClassifier in the pipeline
plot_feature_importance(model_pipeline, X.columns, "Feature Importance - RandomForest with Pipeline")

numeric_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()

plt.figure(figsize=(15,10))
df[numeric_cols].hist(bins=20, layout=(5,5), color="skyblue", edgecolor="black")
plt.suptitle("Distribution of Numeric Features (Post-cleaning)", fontsize=16)
plt.tight_layout()
plt.show()

categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

plt.figure(figsize=(15,5))
for i, col in enumerate(categorical_cols, 1):
    plt.subplot(1, len(categorical_cols), i)
    sns.countplot(x=col, data=df, order=df[col].value_counts().index, palette="Set2")
    plt.title(col)
    plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15,10))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(5, 5, i)
    sns.boxplot(x="Response", y=col, data=df)
    plt.title(f"{col} vs Response")
plt.tight_layout()
plt.show()

plt.figure(figsize=(15,5))
for i, col in enumerate(categorical_cols, 1):
    plt.subplot(1, len(categorical_cols), i)
    sns.countplot(x=col, hue="Response", data=df, palette="Set2")
    plt.title(f"{col} vs Response")
    plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pickle

with open("cleaned_df.pkl", "wb") as f:
    pickle.dump(df, f)

with open("train_test_data.pkl", "wb") as f:
    pickle.dump({
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test
    }, f)

print("Data and splits saved successfully!")

with open("cleaned_df.pkl", "rb") as f:
    df_loaded = pickle.load(f)

with open("train_test_data.pkl", "rb") as f:
    data = pickle.load(f)
X_train_loaded = data["X_train"]
X_test_loaded = data["X_test"]
y_train_loaded = data["y_train"]
y_test_loaded = data["y_test"]

print(df_loaded.head())